#' The synthetically generated control charts.
#'
#' The data is generated by the process in Alcock and Manolopoulos (1999). In OSTSC package, 
#' class 1 aims to Normal status, while class 0 aims to Cyclic, Increasing trend, Decreasing 
#' trend, Upward shift and Downward shift. The imbalance of class 1 and 0 has been set 1:10.
#'
#' @format A time series data with sequence length 60 and observations number 275. 
#' \describe{
#'   The train_y and test_y contain the class label (1 or 0)
#'   The train_x and test_x contain time series sequences (in numeric)
#'   Each sequence occurs in one line.
#' }
#' 
#' @docType data
#' @keywords datasets
#' @name data_synthetic_control
#' @usage data(data_synthetic_control)
#' @source \url{https://archive.ics.uci.edu/ml/datasets/Synthetic+Control+Chart+Time+Series}

dataset_synthetic_control <- function() {
  #load raw data
  data(synthetic_control_TRAIN)
  data(synthetic_control_TEST)
  # set imbalance to 1:10
  train_x <- synthetic_control_TRAIN[26:300,][, -1]
  train_y <- synthetic_control_TRAIN[26:300,][, c(1)]
  test_x <- synthetic_control_TEST[26:300,][, -1]
  test_y <- synthetic_control_TEST[26:300,][, c(1)]
  # transform format to numpy array
  train_x <- matrix(unlist(train_x), ncol = ncol(train_x))
  test_x <- matrix(unlist(test_x), ncol = ncol(test_x))
  # form data
  dataset_synthetic_control <- list("train_x" = train_x, "train_y" = train_y, "test_x" = test_x, "test_y" = test_y)
  # save data
  devtools::use_data(dataset_synthetic_control)
}
