---
title: "Package 'OSTSC'"
author: "Lan Wei"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{OverSamp-tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## OverSamp

The package provides functions to deal with binary classification problems in time series imbalanced
classes. Synthetic balanced samples are generated according to EPSO and ADASYN (H. Cao, X.-L. Li, Y.-K. Woon and S.-K. Ng, 2013).

## Author

    Lan Wei
    Maintainer: Lan Wei <lweicdsor@gmail.com>

## References

    H. Cao, X.-L. Li, Y.-K. Woon and S.-K. Ng, 
    "Integrated Oversampling for Imbalanced Time Series Classification" 
    IEEE Trans. on Knowledge and Data Engineering (TKDE), 
    vol. 25(12), pp. 2809-2822, 2013

## Examples

    # loading data
    data(synthetic_control_TRAIN)   
    # create feature and label data 
    label <- synthetic_control_TRAIN[, c(1)]
    sample <- synthetic_control_TRAIN[, -1] 
    # oversample the class 1 to the same amount of class 0
    MyData <- OSTSC(sample, label, target_class = 1)
    # print the feature data after oversampling
    MyData$sample
    # print the label data after oversampling
    MyData$label
