#' The synthetically generated control charts.
#'
#' The data is generated by the process in Alcock and Manolopoulos (1999). Class 1 aims to Normal status,  
#' while class 0 aims to Cyclic, Increasing trend, Decreasing trend, Upward shift and Downward shift.
#'
#' @format A data frame with 300 rows and 61 variables, with a single chart per line. 
#' \describe{
#'   The first column is the class label (1 or 0)
#'   The other 60 columns constructs a  time series sequence (in numeric)
#'   ...
#' }
#' 
#' @docType data
#' @keywords datasets
#' @name synthetic_control_TEST
#' @usage data(synthetic_control_TEST)
#' @source \url{https://archive.ics.uci.edu/ml/datasets/Synthetic+Control+Chart+Time+Series}
NULL